[package]
name = "rust-forward"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "bridge"
path = "src/bin/bridge.rs"

[[bin]]
name = "forward"
path = "src/bin/forward.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
rustls = { version = "0.23", features = ["aws_lc_rs"] }
anyhow = "1"
log = "0.4"
env_logger = "0.11"
clap = { version = "4", features = ["derive"] }
h3 = { version = "0.0.8" }
h3-quinn = { version = "0.0.10" }
quinn = { version = "0.11", default-features = false, features = ["runtime-tokio", "rustls", "ring"] }
bytes = "1"
webpki-roots = "0.26"
http = "1"
rcgen = "0.14"
socket2 = "0.6"
tokio-socks = "0.5"
h2 = "0.4"
tokio-rustls = "0.26"
rustls-pemfile = "2"

[profile.release]
lto = "fat"
codegen-units = 1
strip = "symbols"
